tap "homebrew/cask"
# set arguments for all 'brew install --cask' commands
cask_args appdir: "/Applications"

brew "asdf"
brew "autojump"
brew "awscli"
brew "circleci"
brew "direnv"
brew "fzf"
brew "git"
brew "gnu-tar"
brew "jid"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "ruby-build"
brew "terraform"
brew "terraform-ls"
brew "thefuck"
brew "tmux"
brew "wget"
brew "yadm"

cask "1password"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "spotify"
