brew 'dep'
brew 'direnv'
brew 'fontconfig'
brew 'freetype'
brew 'geoip'
brew 'git'
brew 'graphviz'
brew 'go'
brew 'heroku'
brew 'highlight'
brew 'hugo'
brew 'imagemagick'
brew 'jid'
brew 'jq'
brew 'mysql@5.6', restart_service: true
brew 'neovim'
brew 'nginx', restart_service: true
brew 'node'
brew 'phantomjs'
brew 'postgresql', restart_service: true
brew 'rbenv'
brew 'redis', restart_service: true
brew 'ripgrep'
brew 'ruby-build'
brew 'rust'
brew 'sqlite'
brew 'stern'
brew 'wget'
brew 'yadm'

tap 'caskroom/cask'
cask_args appdir: '/Applications'
tap 'caskroom/fonts'

cask 'iterm2'
cask 'font-hack-nerd-font'
cask 'jet'
