#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  echo "Updating yadm submodules"
  yadm submodule update --init --recursive

  if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
    echo "Downloading vim-plug"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  echo "Bootstrapping neovim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'

  # if [ -d "$HOME/.iterm2" ]; then
  #   echo "Configuring iterm2"
  #   defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  # fi

fi
